### ISSUE TITLE
How do you generate nnpack.sln?

### ISSUE THREAD

**Issue by FreeApe** [zeno40/nnpack-windows#1]
Hi, My VS version is 2015,  How do you generate nnpack.sln？I want to generate it by myself, and What is detials that  i need to notice?  I have installed PeachPy successfully , and I try to generate nnpack.sln by CMake-GUI tool, but I can not build it success. Thx.

**Comment by zeno40** [comment]
I've just changed the default project files to use VS2015 instead of VS2017. The solutions file nnpack.sln is not compatible with VS2015. The easiest way is to delete the included nnpack.sln file and open nnpack.vcxproj in VS2015. Optionally you can add /googletest/googletest/msvc/2010/gtest.vcxproj and /test/test.vcxproj if you want to tun the unit tests yourself. Now compile the projects and save the solution as nnpack.sln

**Comment by FreeApe** [comment]
Thanks for your replay. There is a error while I build with VS2015 with the last commit(e0b483b559) : 

```
 error MSB8036: The Windows SDK version 10.0.15063.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```

so, It is nice to  use CMakeLists.txt to generate the VS project.
